import './styles/tokens.css';
import './styles/base.css';
import './styles/sections.css';
import { initHeroVideo } from './js/hero-video.js';
import { initNav } from './js/nav.js';
import { initReveal } from './js/reveal.js';
import { initParallax } from './js/parallax.js';
import { initLightbox } from './js/lightbox.js';
import { initThumbPreview } from './js/thumb-preview.js';
import { initHalftoneTrail } from './js/halftone-trail.js';
import { initSoftText } from './js/soft-text.js';
import { initCardTilt } from './js/card-tilt.js';
import { initLiveTimestamp } from './js/live-timestamp.js';

initHeroVideo();
initNav();
initReveal();
initParallax();
initLightbox();
initThumbPreview();
initHalftoneTrail();
initSoftText();
initCardTilt();
initLiveTimestamp();
